version: "3.9"

services:
  db:
    image: postgis/postgis
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/django/code
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgis://postgres:postgres@db:5432/postgres
    depends_on:
      - db

volumes:
  postgres_data:
