# Generated by Django 4.0.4 on 2022-07-09 20:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shortener',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('full_url', models.URLField()),
                ('hash_url', models.CharField(max_length=15, unique=True)),
                ('times_followed', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'url',
                'verbose_name_plural': 'urls',
                'ordering': ('-created',),
            },
        ),
    ]
