name: Deploy to Dokku

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master
  
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch'
        required: true
        default: 'master'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10.5]
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      env:
        SECRET_KEY: ${{ env.DJANGO_SECRET_KEY }}
        ALLOWED_HOSTS: ${{ env.ALLOWED_HOSTS }}
      run: |
        python manage.py test
  deploy:
    needs: [test]
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Deploy to master
        if: github.ref == 'refs/heads/master' || (github.event_name == 'workflow_dispatch' && github.event.inputs.branch == 'master')
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@${{ secrets.DOKKU_HOST }}:${{ secrets.SSH_PORT }}/~/smallurl'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}